config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  resources :answers, only: [:show, :edit, :update, :destroy]

  resources :questions do
    resources :answers, only: [:index, :new, :create]
  end


	match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
	match 'auth/failure', to: redirect('/'), via: [:get, :post]
	match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/answer.rb
class Answer < ActiveRecord::Base
 belongs_to :user
 belongs_to :question
 validates :title, presence: true, length: {minimum: 10}
 validates :body, presence: true, length: {minimum: 25}
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  validates :title, presence: true, length: {minimum: 10}
  validates :body, presence: true, length: {minimum: 25}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers
  validates :name, presence: true
  validates :uid, presence: true

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/answers_controller.rb
require 'pry'

class AnswersController < ApplicationController

	def index
		#With nested routes you need to specify the parent id
		@question = @answers.first.question
	end

	def show
		@answer = Answer.find(params[:id])
	end

	def new
    @answer = Answer.new
    @question = Question.find(params[:question_id])
    #Must specify which :id when at the nested level (eg, /questions/:question_id/answers/new)
	end

	def create
	    @answer = Answer.new(answer_params)
	    @answer.user = User.find(session[:user_id])
	    @answer.question = Question.find(params[:question_id])
	    #Don't use .create, it will make the if @answer.save pass automatically (b/c it already saves)
	    if @answer.save
		  	redirect_to question_path(@answer.question)
		  else
		  	flash[:notice] = "We'll eventually put specific error messages here!"
		    render :new
		  end
	end

	def edit
    @answer = Answer.find(params[:id])
	end

	def update
    @answer = Answer.find(params[:id])

    if @answer.update(answer_params)
	  	redirect_to question_path(@answer.question)
	  else
	  	flash[:notice] = "We'll eventually put specific error messages here!"
	    render :edit
	  end
	end

	def destroy
    @answer = Answer.find(params[:id])

    if @answer.destroy
	  	redirect_to question_path(@answer.question)
	  else
	  	flash[:notice] = "We'll eventually put specific error messages here!"
	    render :show
	  end
	end

	private

	def answer_params
	  params.require(:answer).permit(:title, :body, :favorite?)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def index
	  @questions = Question.all.order('created_at DESC')
	end

	def show
	  @question = Question.find(params[:id])
	  @answers = @question.answers
	end

	def new
	  @question = Question.new
	end

	def create
	  @question = Question.new(question_params)
      @question.user = User.find(session[:user_id])
	  if @question.save
	  	redirect_to '/'
	  else
	  	flash[:notice] = "We'll eventually put specific error messages here!"
	    render :new
	  end
	end

	def edit
	  @question = Question.find(params[:id])
	  #Cannot say Question.new here, you're not creating, you're updating!
	end

	def update
	  @question = Question.find(params[:id])

	  if @question.update(question_params)
	  	redirect_to question_path(@question)
	  else
	  	flash[:notice] = "We'll eventually put specific error messages here!"
	    render :edit
	  end
	end

	def destroy
	  @question = Question.find(params[:id])

	  if @question.destroy
	    redirect_to root_path
	  else
	  	flash[:notice] = "We'll eventually put specific error messages here!"
	    render :show
	  end
	end


	private

	def question_params
	  params.require(:question).permit(:title, :body)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create	
  	user = User.from_omniauth(env['omniauth.auth'])
  	session[:user_id] = user.id
  	redirect_to root_url
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_index.html.erb
<% if answers.count > 0 %>
	<h3> Answers for <%= "#{@question.title}" %> </h3>

	<ul>
		<% answers.each do |a| %>

	    <% if a.favorite? %>
 				<h3> Dis Da Best Right Herr </h3>
	    <% end %>

	    <li>
	      <%= link_to "#{a.title}", answer_path(a) %> 
	    </li>

	    <li>
	      <%= "By #{a.user.name} at #{a.created_at}" %>
	    </li>

	    <li>
	      <%= a.body %>
	    </li>
	      <% if session[:user_id] == @question.user_id %>
	        <li>
	          <%= link_to 'Make Favorite!', edit_answer_path(a) %>
	        </li>
	      <% end %>
		<% end %>
	</ul>
<% else %>
  <h3> No answers yet! </h3>

<% end %>

app/views/answers/edit.html.erb
<h2> Correct Your Shitty Wisdom </h2>

<div class='forms'>
  <%= form_for @answer do |f| %>
  
  <% if session[:user_id] == @answer.user_id %>

    <%= f.label :title %>:
    <%= f.text_field :title %><br>

    <%= f.label :body %>:
    <%= f.text_field :body %><br>

  <% end %>

  <% if session[:user_id] == @answer.question.user_id %>
    <%= f.label :favorite? %>:
    <%= f.check_box :favorite? %><br>
  <% end %>

  <%= f.submit :'Update' %>

  <% end %>
</div>

app/views/answers/index.html.erb
<h2> Answers for <%= "#{@question.title}" %> </h2>

<ul>
	<% @answers.each do |a| %>
    <li>
      <%= link_to "#{a.title}", answer_path(a) %> 
    </li>
    <li>
      <%= "By #{a.user.name} at #{a.created_at}" %>
    </li>
	<% end %>
</ul>

app/views/answers/new.html.erb
<h2> Make Your Wisdom Writ </h2>

<div class='forms'>
  <%= form_for [@question, @answer] do |f| %>
  <!-- must tell the form it is for the question of a specific answer -->
  <%= f.label :title %>:
  <%= f.text_field :title %><br>

  <%= f.label :body %>:
  <%= f.text_field :body %><br>

  <%= f.submit %>

  <% end %>
</div>

app/views/answers/show.html.erb
<h2><%= @answer.title %></h2>

<% if session[:user_id] == @answer.user_id %>
	<header>
	  <p>
	    <%= link_to 'Edit', edit_answer_path(@answer) %>
	  </p>

	  <p>
	    <%= link_to 'Delete', answer_path(@answer), method: :delete %>
	  </p>
	</header>
<% end %>

<h4>
  <%= "Posted by #{@answer.user.name} at #{@answer.created_at}" %>
</h4>

<p><%= @answer.body %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRescueMission</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  
    <div id="user_nav">
      <% if current_user %>
        <p> Signed in as <strong><%= current_user.name %></strong>! </p>
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
        <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
      <% end %>
    </div>
    
    <h1> Questions, Answers n' Shit! </h1>
      
    <%= yield %>

    <div class='flash'>
      <h4><%= flash[:notice] %></h4>
    </div>

    <nav>
      <p><a href='/'> Homeward Bound </a></p>
      <p>
        <a href='/questions/new'> Post A Question </a>
      </p>
    </nav>

  </body>
</html>

app/views/questions/edit.html.erb
<h2> Post A Question, Brave Soul </h2>

<div class='forms'>

  <%= form_for @question, method: :patch do |f| %>
  
  <%= f.label :title %>:
  <%= f.text_field :title %><br>

  <%= f.label :body %>:
  <%= f.text_field :body %><br>

  <%= f.label :user_id %>:
  <%= f.text_field :user_id %><br>

  <%= f.submit :'Update' %>

  <% end %>

</div>

app/views/questions/index.html.erb
<h2> Questions </h2>

<ul>
	<% @questions.each do |q| %>
    <li>
      <%= link_to "#{q.title}", question_path(q) %> 
    </li>
    <li>
      <p><%= "Posted by #{q.user.name} at #{q.created_at}." %></p>
    </li>
	<% end %>
</ul>

app/views/questions/new.html.erb
<h2> Post A Question, Brave Soul </h2>

<div class='forms'>
  <%= form_for @question do |f| %>
  
  <%= f.label :title %>:
  <%= f.text_field :title %><br>

  <%= f.label :body %>:
  <%= f.text_field :body %><br>

  <%= f.submit %>

  <% end %>
</div>

app/views/questions/show.html.erb
<h2><%= @question.title %></h2>

<% if session[:user_id] == @question.user_id %>
	<header>
	  <p>
	    <%= link_to 'Edit', edit_question_path(@question) %>
	  </p>

	  <p>
	    <%= link_to 'Delete', question_path(@question), method: :delete %>
	  </p>
	</header>
<% end %>

<h4>
  <%= "Posted by #{@question.user.name} at #{@question.created_at}" %>
</h4>

<p><%= @question.body %></p>

<%= render 'answers/index', answers: @answers %>

<p><%= link_to 'Post Your Answer', new_question_answer_path(@question)  %></p>